name: local-server
core:
  url:
  public_key:
  private_key:
  protocol:
rabbitmq:
  host:
  port:
  username:
  password:
  queue:
  exchange:
github:
  username:
  password:
serviceaccount:
software_repos:
  - cytomine
